vistoria.pdf.pasta-destino=\\\\zanfls01\\scanner\\suporte.zanaflex

# 0.0.0.0 permite acesso de outros dispositivos na mesma rede (ex: celular), nao so localhost
server.address=0.0.0.0
server.port=8080
